#include "ha_discovery_stale.h"

// GENERATED FILE -- do not edit by hand.
// Source: tools/gen_discovery.py
//
// Regenerate with:  python3 tools/gen_discovery.py
//
// The discovery topics earlier firmware published and this one no
// longer does. ha_mqtt.c clears each of them with an empty retained
// payload after publishing the current table, which is what makes Home
// Assistant drop the superseded entities instead of showing them
// forever.
//
// Derived from tools/prev_discovery_topics.txt minus the current table,
// so it cannot drift the way the previous hand-written list did.

const char *const HA_STALE_DISCOVERY_TOPICS[] = {
    "homeassistant/number/spiderfarmer_$D_blower_cycle_off_minutes/config",
    "homeassistant/number/spiderfarmer_$D_blower_cycle_run_minutes/config",
    "homeassistant/number/spiderfarmer_$D_blower_cycle_times/config",
    "homeassistant/number/spiderfarmer_$D_blower_schedule_speed_cycle/config",
    "homeassistant/number/spiderfarmer_$D_blower_schedule_speed_env/config",
    "homeassistant/number/spiderfarmer_$D_blower_schedule_speed_schedule/config",
    "homeassistant/number/spiderfarmer_$D_blower_standby_speed_cycle/config",
    "homeassistant/number/spiderfarmer_$D_blower_standby_speed_env/config",
    "homeassistant/number/spiderfarmer_$D_blower_standby_speed_schedule/config",
    "homeassistant/number/spiderfarmer_$D_fan_cycle_off_minutes/config",
    "homeassistant/number/spiderfarmer_$D_fan_cycle_run_minutes/config",
    "homeassistant/number/spiderfarmer_$D_fan_cycle_times/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level_cycle/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level_env/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level_ppfd_env/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level_schedule/config",
    "homeassistant/number/spiderfarmer_$D_fan_schedule_speed_cycle/config",
    "homeassistant/number/spiderfarmer_$D_fan_schedule_speed_env/config",
    "homeassistant/number/spiderfarmer_$D_fan_schedule_speed_schedule/config",
    "homeassistant/number/spiderfarmer_$D_fan_standby_speed_cycle/config",
    "homeassistant/number/spiderfarmer_$D_fan_standby_speed_env/config",
    "homeassistant/number/spiderfarmer_$D_fan_standby_speed_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light_dim_threshold_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_dim_threshold_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light_fade_minutes_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light_off_threshold_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_off_threshold_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light_ppfd_fade_minutes_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_ppfd_max_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_ppfd_min_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_ppfd_target_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light_schedule_brightness_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light2_fade_minutes_schedule/config",
    "homeassistant/number/spiderfarmer_$D_light2_ppfd_fade_minutes_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light2_ppfd_max_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light2_ppfd_min_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light2_ppfd_target_ppfd/config",
    "homeassistant/number/spiderfarmer_$D_light2_schedule_brightness_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_co2_deadband_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_co2_target_day_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_co2_target_night_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_humi_deadband_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_humi_target_day_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_humi_target_night_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_temp_deadband_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_temp_target_day_schedule/config",
    "homeassistant/number/spiderfarmer_$D_target_temp_target_night_schedule/config",
    "homeassistant/select/spiderfarmer_$D_blower_cycle_times_env/config",
    "homeassistant/select/spiderfarmer_$D_blower_cycle_times_schedule/config",
    "homeassistant/select/spiderfarmer_$D_blower_env_submode_env/config",
    "homeassistant/select/spiderfarmer_$D_blower_env_submode_schedule/config",
    "homeassistant/select/spiderfarmer_$D_blower_main_mode_env/config",
    "homeassistant/select/spiderfarmer_$D_blower_main_mode_schedule/config",
    "homeassistant/select/spiderfarmer_$D_fan_cycle_times_env/config",
    "homeassistant/select/spiderfarmer_$D_fan_cycle_times_schedule/config",
    "homeassistant/select/spiderfarmer_$D_fan_env_submode_env/config",
    "homeassistant/select/spiderfarmer_$D_fan_env_submode_schedule/config",
    "homeassistant/select/spiderfarmer_$D_fan_main_mode_env/config",
    "homeassistant/select/spiderfarmer_$D_fan_main_mode_schedule/config",
    "homeassistant/switch/spiderfarmer_$D_fan_natural_wind_cycle/config",
    "homeassistant/switch/spiderfarmer_$D_fan_natural_wind_env/config",
    "homeassistant/switch/spiderfarmer_$D_fan_natural_wind_schedule/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_off_time_env/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_off_time_schedule/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_run_time_env/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_run_time_schedule/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_start/config",
    "homeassistant/text/spiderfarmer_$D_blower_schedule_end/config",
    "homeassistant/text/spiderfarmer_$D_blower_schedule_start/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_off_time_env/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_off_time_schedule/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_run_time_env/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_run_time_schedule/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_start/config",
    "homeassistant/text/spiderfarmer_$D_fan_schedule_end/config",
    "homeassistant/text/spiderfarmer_$D_fan_schedule_start/config",
    "homeassistant/text/spiderfarmer_$D_light_ppfd_end/config",
    "homeassistant/text/spiderfarmer_$D_light_ppfd_start/config",
    "homeassistant/text/spiderfarmer_$D_light_schedule_end/config",
    "homeassistant/text/spiderfarmer_$D_light_schedule_start/config",
    "homeassistant/time/spiderfarmer_$D_blower_cycle_start_env/config",
    "homeassistant/time/spiderfarmer_$D_blower_cycle_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_blower_schedule_end_schedule/config",
    "homeassistant/time/spiderfarmer_$D_blower_schedule_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_fan_cycle_start_env/config",
    "homeassistant/time/spiderfarmer_$D_fan_cycle_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_fan_schedule_end_schedule/config",
    "homeassistant/time/spiderfarmer_$D_fan_schedule_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_light_ppfd_end_ppfd/config",
    "homeassistant/time/spiderfarmer_$D_light_ppfd_start_ppfd/config",
    "homeassistant/time/spiderfarmer_$D_light_schedule_end_schedule/config",
    "homeassistant/time/spiderfarmer_$D_light_schedule_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_light2_ppfd_end_ppfd/config",
    "homeassistant/time/spiderfarmer_$D_light2_ppfd_start_ppfd/config",
    "homeassistant/time/spiderfarmer_$D_light2_schedule_end_schedule/config",
    "homeassistant/time/spiderfarmer_$D_light2_schedule_start_schedule/config",
    "homeassistant/time/spiderfarmer_$D_target_day_time_end_schedule/config",
    "homeassistant/time/spiderfarmer_$D_target_day_time_start_schedule/config",
    "homeassistant/fan/$D_fan/config",
    "homeassistant/fan/$D_blower/config",
    "homeassistant/number/spiderfarmer_$D_light_fade_minutes/config",
    "homeassistant/number/spiderfarmer_$D_light_ppfd_fade_minutes/config",
    "homeassistant/number/spiderfarmer_$D_blower_schedule_speed/config",
    "homeassistant/number/spiderfarmer_$D_blower_standby_speed/config",
    "homeassistant/number/spiderfarmer_$D_fan_oscillation_level/config",
    "homeassistant/number/spiderfarmer_$D_fan_schedule_speed/config",
    "homeassistant/number/spiderfarmer_$D_fan_standby_speed/config",
    "homeassistant/number/spiderfarmer_$D_light2_dim_threshold/config",
    "homeassistant/number/spiderfarmer_$D_light2_fade_minutes/config",
    "homeassistant/number/spiderfarmer_$D_light2_off_threshold/config",
    "homeassistant/number/spiderfarmer_$D_light2_ppfd_fade_minutes/config",
    "homeassistant/number/spiderfarmer_$D_light_dim_threshold/config",
    "homeassistant/number/spiderfarmer_$D_light_off_threshold/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_off_time/config",
    "homeassistant/text/spiderfarmer_$D_blower_cycle_run_time/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_off_time/config",
    "homeassistant/text/spiderfarmer_$D_fan_cycle_run_time/config",
    "homeassistant/select/spiderfarmer_$D_fan_main_mode/config",
    "homeassistant/select/spiderfarmer_$D_fan_env_submode/config",
    "homeassistant/select/spiderfarmer_$D_blower_main_mode/config",
    "homeassistant/select/spiderfarmer_$D_blower_env_submode/config",
    "homeassistant/switch/spiderfarmer_$D_sensor_heating/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_seedling/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_clone/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_veg/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_flower/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_dry/config",
    "homeassistant/button/spiderfarmer_$D_plan_template_custom/config",
    "homeassistant/switch/spiderfarmer_$D_fan_oscillation/config",
    "homeassistant/select/spiderfarmer_$D_fan_oscillation_level/config",
};

const size_t HA_STALE_DISCOVERY_COUNT = sizeof(HA_STALE_DISCOVERY_TOPICS) / sizeof(HA_STALE_DISCOVERY_TOPICS[0]);
