#!/usr/bin/env python3
"""Extract the bridge's web interface into a static demo (GitHub Pages).

The web GUI lives in the firmware as C string constants (one per page). This
script pulls those constants out of the sources, assembles them into
standalone HTML files under demo/, rewrites the navigation to relative links
and injects the fetch-interception faker (demo/faker.js), which answers every
JSON endpoint with randomized demo data. POSTs are simulated as successful.

Run from the repository root:

    python3 scripts/extract_gui.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / "firmware" / "ggs" / "main"
OUT = ROOT / "demo"

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "'": "'", "\\": "\\", "0": "\0"}


def extract_const(text: str, name: str):
    """Return the joined value of a `static const char NAME[] = "..." "...";`."""
    m = re.search(r"const char %s\s*\[\s*\]\s*=" % re.escape(name), text)
    if not m:
        return None
    i = m.end()
    parts, buf, in_str = [], [], False
    while i < len(text):
        c = text[i]
        if not in_str:
            if c == "/" and i + 1 < len(text) and text[i + 1] == "/":
                # line comment: skip to end of line (a ';' inside must not
                # terminate the constant)
                while i < len(text) and text[i] != "\n":
                    i += 1
            elif c == "/" and i + 1 < len(text) and text[i + 1] == "*":
                i += 2
                while i + 1 < len(text) and not (text[i] == "*" and text[i + 1] == "/"):
                    i += 1
                i += 1
            elif c == '"':
                in_str, buf = True, []
            elif c == ";":
                break
        else:
            if c == "\\":
                nxt = text[i + 1]
                buf.append(ESCAPES.get(nxt, nxt))
                i += 1
            elif c == '"':
                parts.append("".join(buf))
                in_str = False
            else:
                buf.append(c)
        i += 1
    return "".join(parts)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


BANNER = """
<div id="sbdemo" style="background:#fbbf24;color:#13151a;font:600 .8rem system-ui;
padding:.45rem .8rem;text-align:center">
  DEMO — all data here is simulated. This is the real bridge interface, rendered offline with
  <a href="https://github.com/matthias1232/spider-farmer-homeassistant">SpiderBridge</a>'s
  faker. Built and tested with this
  <a href="https://www.amazon.de/dp/B0DHRV7784?&linkCode=ll2&tag=matthias1232-20&linkId=c71aee711cb280677528abe8e058e53c&ref_=as_li_ss_tl">ESP32 board</a>
  · <a href="https://www.paypal.com/paypalme/matthias1232">Donate</a>
</div>"""


def faker_script_tag(depth: int) -> str:
    return '<script src="%sfaker.js"></script>' % ("../" * depth)


def compose(style: str, nav_html: str, body_open: str, body: str) -> str:
    page = style
    page += "\n" + nav_html + "\n" + body_open + "\n" + body
    # inject the demo banner directly after <body>
    page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
    # inject the faker before the closing tags
    page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(1), 1)
    return page


# ---------------------------------------------------------------------------
# The Settings page (/) is generated by C code with live values, so it cannot
# be extracted byte-for-byte. This replica keeps the same look (PAGE_STYLE) and
# the same fields, and posts to the same /save endpoint (faked).
SETTINGS_BODY = """
<h1>SpiderBridge Settings</h1>
<form method="POST" action="/save" onsubmit="return demoSave(event)">
<input type=hidden name="form" value="full">
<fieldset><legend>Networking — home Wi-Fi</legend>
<label>Network name (SSID)</label><input type=text name="sta_ssid" placeholder="MyHomeWiFi">
<label>Password</label><input type=password name="sta_pass" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;">
<small>The bridge uses this network to reach your MQTT broker and Home Assistant.</small>
</fieldset>
<fieldset><legend>Hotspot (setup network)</legend>
<label>Hotspot name</label><input type=text name="ap_ssid" value="SpiderBridge">
<label>Hotspot password</label><input type=password name="ap_pass" value="12345678">
<small>Change the hotspot password, or generate a new one. Default after install:
<code>12345678</code> at <code>192.168.10.1</code>.</small>
<label class=inline><input type=checkbox name="ap_gen"> Generate a new password</label>
</fieldset>
<fieldset><legend>MQTT broker</legend>
<label>Broker</label><input type=text name="mqtt_uri" value="mqtt://homeassistant.local:1883">
<label>User (optional)</label><input type=text name="mqtt_user">
<label>Password (optional)</label><input type=password name="mqtt_pass">
</fieldset>
<fieldset><legend>Controller — Bluetooth</legend>
<label class=inline><input type=checkbox checked> Bridge as a Wi-Fi hotspot for the controller</label>
<label class=inline><input type=checkbox name="wan_block"> Cut the controller's own internet access</label>
<small>Scan, connect and unpair controllers under <em>Control → Bluetooth</em>.</small>
</fieldset>
<fieldset><legend>Time</legend>
<label>Time zone</label>
<select name="tz">
  <option>Europe/Berlin</option><option>Europe/London</option>
  <option>America/New_York</option><option>UTC</option>
</select>
<label class=inline><input type=checkbox name="dst_auto" checked> Daylight saving by zone rules</label>
<label class=inline><input type=checkbox name="tz_push" checked> Push these time settings to every controller</label>
</fieldset>
<button type=submit>Save</button>
</form>
<div class=info>Demo mode: the form is not submitted anywhere — the real interface saves
to the bridge's configuration and reboots the connection.</div>
<script>
async function demoSave(ev){
  ev.preventDefault();
  const data = new FormData(ev.target);
  const body = new URLSearchParams(data).toString();
  try{
    const r = await fetch('/save',{method:'POST',headers:{
      'Content-Type':'application/x-www-form-urlencoded'},body:body});
    alert(r.ok ? 'Saved (demo)' : 'Save failed (demo)');
  }catch(e){ alert('Saved (demo)'); }
  return false;
}
</script>
"""


def nav_html(entries, current: str) -> str:
    out = ['<div class="topnav"><span class="brand">SpiderBridge</span>']
    for page_id, href, label in entries:
        cls = ' class="cur"' if href == current else ""
        out.append('<a href="%s"%s>%s</a>' % (href, cls, label))
    out.append("</div>")
    return "".join(out)


PAGES = {
    #  href        depth  file            style const        body-open const     body const
    "/control":  (1, "control/index.html", "control_page.c", "CONTROL_PAGE", "CONTROL_BODY_OPEN", "CONTROL_PAGE_BODY"),
    "/status":   (1, "status/index.html",  "status_page.c",  "STATUS_PAGE",  "STATUS_BODY_OPEN",  "STATUS_PAGE_BODY"),
    "/network":  (1, "network/index.html", "network_page.c", "NETWORK_PAGE", "NETWORK_BODY_OPEN", "NETWORK_PAGE_BODY"),
    "/log":      (1, "log/index.html",     "config_portal.c", "LOG_PAGE",    "LOG_BODY_OPEN",     "LOG_PAGE_BODY"),
}


def rel_href(target: str, current: str, depth: int) -> str:
    dirs = {"/": "", "/control": "control", "/status": "status",
            "/network": "network", "/log": "log", "/update": "update"}
    if target == current:
        return "#"
    prefix = "../" * depth
    target_dir = dirs[target]
    if not target_dir:
        return prefix or "./"
    return prefix + target_dir + "/"


def main() -> int:
    out = OUT
    (out / "control").mkdir(parents=True, exist_ok=True)
    (out / "status").mkdir(parents=True, exist_ok=True)
    (out / "network").mkdir(parents=True, exist_ok=True)
    (out / "log").mkdir(parents=True, exist_ok=True)
    (out / "update").mkdir(parents=True, exist_ok=True)

    nav_src = read(MAIN / "nav.c")
    nav_style = extract_const(nav_src, "NAV_STYLE")
    entries = re.findall(
        r'\{\s*NAV_\w+,\s*"([^"]+)",\s*"([^"]+)"\s*\}', nav_src
    )
    entries = [(href, href, label) for href, label in entries]

    written = []

    # ---- Settings (static replica) ----------------------------------------
    portal = read(MAIN / "config_portal.c")
    style = extract_const(portal, "PAGE_STYLE")
    body_open = extract_const(portal, "PAGE_BODY_OPEN") or "</style></head><body>"
    nav = nav_html(entries, "/").replace(
        'href="/control"', 'href="control/"'
    ).replace(
        'href="/status"', 'href="status/"'
    ).replace(
        'href="/network"', 'href="network/"'
    ).replace(
        'href="/log"', 'href="log/"'
    ).replace(
        'href="/update"', 'href="update/"'
    ).replace(
        'href="/"', 'href="index.html"'
    )
    page = style + "\n" + nav + "\n" + body_open + "\n" + SETTINGS_BODY + "\n</body></html>"
    page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
    page = page.replace("</body></html>", "<script src=\"faker.js\"></script></body></html>", 1)
    (out / "index.html").write_text(page, encoding="utf-8")
    written.append("index.html")

    # ---- JS-driven pages ---------------------------------------------------
    for href, (depth, rel, srcfile, style_c, open_c, body_c) in PAGES.items():
        src = read(MAIN / srcfile)
        style = extract_const(src, style_c)
        body_open = extract_const(src, open_c) or "</style></head><body>"
        body = extract_const(src, body_c)
        if not (style and body):
            print("WARN: could not extract %s from %s" % (body_c, srcfile), file=sys.stderr)
            continue
        nav = nav_html(entries, href)
        nav = re.sub(r'href="(/[^"]*)"', lambda m: 'href="%s"' % rel_href(m.group(1), href, depth), nav)
        page = style + "\n" + nav + "\n" + body_open + "\n" + body
        page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
        page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(depth), 1)
        (out / rel).write_text(page, encoding="utf-8")
        written.append(rel)

    # ---- Firmware update page ----------------------------------------------
    ota = read(MAIN / "ota_update.c")
    head = extract_const(ota, "OTA_PAGE_HEAD")
    open_ = extract_const(ota, "OTA_PAGE_BODY_OPEN")
    tail = extract_const(ota, "OTA_PAGE_TAIL")
    if head and open_ and tail:
        nav = nav_html(entries, "/update")
        nav = re.sub(r'href="(/[^"]*)"', lambda m: 'href="%s"' % rel_href(m.group(1), "/update", 1), nav)
        page = head + "\n" + nav + "\n" + open_ + "\n" + tail
        page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
        page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(1), 1)
        (out / "update" / "index.html").write_text(page, encoding="utf-8")
        written.append("update/index.html")
    else:
        print("WARN: could not extract OTA page", file=sys.stderr)

    print("Demo pages written: %s" % ", ".join(written))
    print("Next: demo/faker.js supplies the fake data for these pages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
