#!/usr/bin/env python3
"""Build the GitHub Pages demo of the bridge's web interface.

The JS-driven pages (Control, Status, Network, MQTT log) live in the firmware
as C string constants, and the Firmware page is assembled from constants in
ota_update.c. This script pulls those out of the sources, assembles them into
standalone HTML files under demo/, rewrites the navigation to relative links
and injects the fetch-interception faker (demo/faker.js), which answers every
JSON endpoint with randomized demo data. POSTs are simulated as successful.

The Settings page (/) is generated by C from live configuration values and
cannot be extracted as a constant. It is kept 1:1 with the real page via a
sanitised capture (scripts/settings_template.html, produced by
scripts/capture_settings.py). The placeholders in that template are filled
here with neutral demo values, and demo/faker.js randomizes them at runtime.

Run from the repository root:

    python3 scripts/extract_gui.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MAIN = ROOT / "firmware" / "ggs" / "main"
OUT = ROOT / "demo"
SETTINGS_TEMPLATE = ROOT / "scripts" / "settings_template.html"

ESCAPES = {"n": "\n", "t": "\t", "r": "\r", '"': '"', "'": "'", "\\": "\\", "0": "\0"}


def extract_const(text: str, name: str):
    """Return the joined value of a `static const char NAME[] = "..." "...";`."""
    m = re.search(r"const char %s\s*\[\s*\]\s*=" % re.escape(name), text)
    if not m:
        return None
    i = m.end()
    parts, buf, in_str = [], [], False
    while i < len(text):
        c = text[i]
        if not in_str:
            if c == "/" and i + 1 < len(text) and text[i + 1] == "/":
                # line comment: skip to end of line (a ';' inside must not
                # terminate the constant)
                while i < len(text) and text[i] != "\n":
                    i += 1
            elif c == "/" and i + 1 < len(text) and text[i + 1] == "*":
                i += 2
                while i + 1 < len(text) and not (text[i] == "*" and text[i + 1] == "/"):
                    i += 1
                i += 1
            elif c == '"':
                in_str, buf = True, []
            elif c == ";":
                break
        else:
            if c == "\\":
                nxt = text[i + 1]
                buf.append(ESCAPES.get(nxt, nxt))
                i += 1
            elif c == '"':
                parts.append("".join(buf))
                in_str = False
            else:
                buf.append(c)
        i += 1
    return "".join(parts)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


BANNER = """
<div id="sbdemo" style="background:#fbbf24;color:#13151a;font:600 .8rem system-ui;
padding:.45rem .8rem;text-align:center">
  DEMO — all data here is simulated. This is the real bridge interface, rendered offline with
  <a href="https://github.com/matthias1232/spider-farmer-homeassistant">SpiderBridge</a>'s
  faker. Built and tested with this
  <a href="https://www.amazon.de/dp/B0DHRV7784?&linkCode=ll2&tag=matthias1232-20&linkId=c71aee711cb280677528abe8e058e53c&ref_=as_li_ss_tl">ESP32 board</a>
  · <a href="https://www.paypal.com/paypalme/matthias1232">Donate</a>
</div>"""


def faker_script_tag(depth: int) -> str:
    return '<script src="%sfaker.js"></script>' % ("../" * depth)


def compose(style: str, nav_html: str, body_open: str, body: str) -> str:
    page = style
    page += "\n" + nav_html + "\n" + body_open + "\n" + body
    # inject the demo banner directly after <body>
    page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
    # inject the faker before the closing tags
    page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(1), 1)
    return page


# Neutral values for the placeholders in scripts/settings_template.html. They
# are clearly generic (no personal data) and demo/faker.js randomizes them on
# every page load, so the hosted demo never shows the same details twice.
SETTINGS_VALUES = {
    "STA_SSID": "MyHomeWiFi",
    "STATIC_IP": "192.168.1.50",
    "STATIC_GW": "192.168.1.1",
    "AP_SSID": "SpiderBridge",
    "AP_PASS": "12345678",
    "AP_SUBNET": "192.168.4.0/24",
    "MQTT_URI": "mqtt://192.168.1.10:1883",
    "MQTT_USER": "homeassistant",
    "HA_URI": "mqtt://192.168.1.10:1883",
    "HA_USER": "homeassistant",
    "SLOG_PORT": "514",
    "SLOG_CA": "",
    "MQTT_CA": "",
    "BR_SUFFIX": "A1B2C3",
    "RESOLVER": "192.168.1.1",
}

# Internal navigation as it appears on the live pages -> the demo location.
SETTINGS_LINKS = [
    ('href="/"', 'href="index.html"'),
    ('href="/control"', 'href="control/"'),
    ('href="/status"', 'href="status/"'),
    ('href="/network"', 'href="network/"'),
    ('href="/log"', 'href="log/"'),
    ('href="/update"', 'href="update/"'),
]


def build_settings(nav_style: str) -> str:
    portal = read(MAIN / "config_portal.c")
    style = extract_const(portal, "PAGE_STYLE")
    body_open = extract_const(portal, "PAGE_BODY_OPEN") or "</style></head><body>"
    body = read(SETTINGS_TEMPLATE)
    # drop the provenance comment written by capture_settings.py
    body = re.sub(r"^\s*<!--.*?-->\s*", "", body, count=1, flags=re.S)
    for key, val in SETTINGS_VALUES.items():
        body = body.replace("{{%s}}" % key, val)
    if "{{" in body:
        leftover = re.findall(r"\{\{\w+\}\}", body)
        print("WARN: unfilled placeholders: %s" % ", ".join(sorted(set(leftover))),
              file=sys.stderr)
    for old, new in SETTINGS_LINKS:
        body = body.replace(old, new)
    page = style + nav_style + body_open + body + "</body></html>"
    page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
    page = page.replace("</body></html>", '<script src="faker.js"></script></body></html>', 1)
    return page


def nav_html(entries, current: str) -> str:
    out = ['<div class="topnav"><span class="brand">SpiderBridge</span>']
    for page_id, href, label in entries:
        cls = ' class="cur"' if href == current else ""
        out.append('<a href="%s"%s>%s</a>' % (href, cls, label))
    out.append("</div>")
    return "".join(out)


# The "Running firmware" fieldset of /update is generated by C code with live
# values, so it is replicated statically here (same markup as the firmware).
OTA_RUNNING = (
    '<fieldset><legend>Running firmware</legend>'
    '<div class=row><span class=lbl>Version</span><span>1.20.4</span></div>'
    '<div class=row><span class=lbl>Project</span><span>spiderbridge_esp32_v2</span></div>'
    '<div class=row><span class=lbl>Built</span><span>Oct  8 2026 19:05:14</span></div>'
    '<div class=row><span class=lbl>IDF</span><span>v5.3.2</span></div>'
    '<div class=row><span class=lbl>Active slot</span><span>ota_1</span></div>'
    '<div class=row><span class=lbl>Update goes to</span><span>ota_0</span></div>'
    '</fieldset>'
)


PAGES = {
    #  href        depth  file            style const        body-open const     body const
    "/control":  (1, "control/index.html", "control_page.c", "CONTROL_PAGE", "CONTROL_BODY_OPEN", "CONTROL_PAGE_BODY"),
    "/status":   (1, "status/index.html",  "status_page.c",  "STATUS_PAGE",  "STATUS_BODY_OPEN",  "STATUS_PAGE_BODY"),
    "/network":  (1, "network/index.html", "network_page.c", "NETWORK_PAGE", "NETWORK_BODY_OPEN", "NETWORK_PAGE_BODY"),
    "/log":      (1, "log/index.html",     "config_portal.c", "LOG_PAGE",    "LOG_BODY_OPEN",     "LOG_PAGE_BODY"),
}


def rel_href(target: str, current: str, depth: int) -> str:
    dirs = {"/": "", "/control": "control", "/status": "status",
            "/network": "network", "/log": "log", "/update": "update"}
    prefix = "../" * depth
    target_dir = dirs[target]
    if not target_dir:
        return prefix or "./"
    return prefix + target_dir + "/"


def main() -> int:
    out = OUT
    (out / "control").mkdir(parents=True, exist_ok=True)
    (out / "status").mkdir(parents=True, exist_ok=True)
    (out / "network").mkdir(parents=True, exist_ok=True)
    (out / "log").mkdir(parents=True, exist_ok=True)
    (out / "update").mkdir(parents=True, exist_ok=True)

    nav_src = read(MAIN / "nav.c")
    nav_style = extract_const(nav_src, "NAV_STYLE")
    entries = re.findall(
        r'\{\s*NAV_\w+,\s*"([^"]+)",\s*"([^"]+)"\s*\}', nav_src
    )
    entries = [(href, href, label) for href, label in entries]

    written = []

    # ---- Settings (1:1 capture, sanitised) --------------------------------
    (out / "index.html").write_text(build_settings(nav_style), encoding="utf-8")
    written.append("index.html")

    # ---- JS-driven pages ---------------------------------------------------
    for href, (depth, rel, srcfile, style_c, open_c, body_c) in PAGES.items():
        src = read(MAIN / srcfile)
        style = extract_const(src, style_c)
        body_open = extract_const(src, open_c) or "</style></head><body>"
        body = extract_const(src, body_c)
        if not (style and body):
            print("WARN: could not extract %s from %s" % (body_c, srcfile), file=sys.stderr)
            continue
        nav = nav_html(entries, href)
        nav = re.sub(r'href="(/[^"]*)"', lambda m: 'href="%s"' % rel_href(m.group(1), href, depth), nav)
        page = style + nav_style + body_open + nav + body
        page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
        page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(depth), 1)
        (out / rel).write_text(page, encoding="utf-8")
        written.append(rel)

    # ---- Firmware update page ----------------------------------------------
    ota = read(MAIN / "ota_update.c")
    head = extract_const(ota, "OTA_PAGE_HEAD")
    open_ = extract_const(ota, "OTA_PAGE_BODY_OPEN")
    tail = extract_const(ota, "OTA_PAGE_TAIL")
    if head and open_ and tail:
        nav = nav_html(entries, "/update")
        nav = re.sub(r'href="(/[^"]*)"', lambda m: 'href="%s"' % rel_href(m.group(1), "/update", 1), nav)
        page = head + nav_style + open_ + nav + OTA_RUNNING + tail
        page = page.replace("</style></head><body>", "</style></head><body>" + BANNER, 1)
        page = page.replace("</body></html>", "%s</body></html>" % faker_script_tag(1), 1)
        (out / "update" / "index.html").write_text(page, encoding="utf-8")
        written.append("update/index.html")
    else:
        print("WARN: could not extract OTA page", file=sys.stderr)

    print("Demo pages written: %s" % ", ".join(written))
    print("Next: demo/faker.js supplies the fake data for these pages.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
